baseURL = "https://navcoin.org"
theme = "navcoin"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
twitter_username = "navcoin"
enableRobotsTXT = true
disableKinds = [
  "home"
  "section",
  "taxonomy"
  "term"
]
