[context.production.environment]
HUGO_VERSION = "0.88.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"

[build]
publish = "public"
command = "hugo"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
